title: "PlayStation Documentation"

encoding: UTF-8



collections:
    docs:
        output: true
        permalink: /
    static:
        output: false
        permalink: /static

defaults:
    - scope:
          path: ""
          type: docs
      values:
          layout: page
